Changed sql in question_find_by_userid_and_created_at
alexandrgurin25/gpt_v01 pull request #3
Opened 2024-03-15 15:33 UTC by alexandrgurin25

2024-03-15 15:37 UTC, Vlad104 requested changes

2024-03-16 08:16 UTC, Vlad104 commented on internal/service/question_service/service.go
> +	countQuestions, err := s.repo.CountQuestionsByUserIdAtToday(userId)
методы ниже countAvailableQuestions, filterUserId итд еще где-то используются?

2024-03-16 08:16 UTC, Vlad104 commented on internal/repository/question_repository/question_find_by_userId_and_createdAt.go
> +		"SELECT COUNT(*) FROM questions WHERE user_id = $1 and created_at > NOW() - INTERVAL '1 day'",
Мысль верная, но не стоит строго записывать бизнес правила в запрос. Время от которого начинаем подсчет должно передаваться аргументом в метод репозитория

2024-03-19 06:31 UTC, Vlad104 commented on internal/app/app.go
> +			//fmt.Println(update.Message.Chat.ID)
комментарий

2024-03-19 06:31 UTC, Vlad104 commented on internal/database/migrations/002_init.up.sql
> +ALTER TABLE questions DROP CONSTRAINT fk_questions_user_id;
зачем questions создавать ?

2024-03-19 06:31 UTC, Vlad104 commented on internal/service/telegram_user_service/service.go
> +func (s *Service) CreateFieldUserId(chatId int64) (*entity.TelegramUser, error) {
Почему Field?

2024-03-19 06:31 UTC, Vlad104 commented on internal/telegram/handlers/add_user_handler/handler.go
> +
нет обработки ошики

2024-03-19 06:31 UTC, Vlad104 commented on internal/telegram/handlers/create_question_handler/create_questions.go
> +	telegram_service *telegram_user_service.Service
поля и переменные надо в camelCase называть. Только имена пакетов исключения

2024-03-20 08:11 UTC, alexandrgurin25 commented on internal/database/migrations/002_init.up.sql
> +ALTER TABLE questions DROP CONSTRAINT fk_questions_user_id;
Я выдавал доступ к изменению таблицы questions, нужно было решить как-то эту проблему

2024-03-20 08:23 UTC, merged

2024-03-20 10:28 UTC, Vlad104 commented on internal/database/migrations/002_init.up.sql
> +ALTER TABLE questions DROP CONSTRAINT fk_questions_user_id;
Не понял, какую проблему?